spring.application.name=Vehicle-Rental-Service
# Server port
server.port=8080

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/vehicle_rental3
spring.datasource.username=shubham
spring.datasource.password=shubham
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Config
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG
